"""
MODULE 7: C Code Generator
============================
Generates TinyML-compatible C code from the quantized IR graph.

Generates:
  1. Model weights as static int8_t arrays
  2. Layer functions (conv2d_int8, linear_int8, etc.)
  3. Inference function: void run_model(int8_t* input, int8_t* output)

Constraints:
  - Fixed-point arithmetic only
  - No dynamic memory allocation
  - Static buffers only
"""

import os
import numpy as np
from typing import List
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from ir.ir_builder import IRGraph, IRNode, OpType


class CCodeGenerator:
    """Generates C code for TinyML MCU deployment."""

    def __init__(self, ir_graph: IRGraph, output_dir: str = "generated", verbose: bool = True):
        self.graph = ir_graph
        self.output_dir = output_dir
        self.verbose = verbose

    def generate(self) -> str:
        """Generate all C files and return the main file path."""
        os.makedirs(self.output_dir, exist_ok=True)

        # Generate model_weights.h
        weights_code = self._generate_weights_header()
        self._write_file("model_weights.h", weights_code)

        # Generate model_ops.h (layer operations)
        ops_code = self._generate_ops_header()
        self._write_file("model_ops.h", ops_code)

        # Generate model.h (main header)
        header_code = self._generate_main_header()
        self._write_file("model.h", header_code)

        # Generate model.c (inference function)
        model_code = self._generate_model_c()
        self._write_file("model.c", model_code)

        self._log(f"Generated C code in {self.output_dir}/")
        return os.path.join(self.output_dir, "model.c")

    def _generate_weights_header(self) -> str:
        """Generate header file with all model weights as static arrays."""
        lines = [
            "/* Auto-generated by TinyML Compiler */",
            "/* Model weights - INT8 quantized */",
            f"/* Model: {self.graph.model_name} */",
            "",
            "#ifndef MODEL_WEIGHTS_H",
            "#define MODEL_WEIGHTS_H",
            "",
            "#include <stdint.h>",
            "",
        ]

        for node in self.graph.get_compute_nodes():
            if node.eliminated or node.weight is None:
                continue

            w = node.weight_int8 if node.weight_int8 is not None else \
                np.clip(np.round(node.weight), -128, 127).astype(np.int8)

            # Write weight array
            safe_name = node.name.replace('.', '_')
            lines.append(f"/* {node.name}: {node.op_type.value} */")
            lines.append(f"/* Shape: {w.shape}, Scale: {node.weight_scale:.6f}, ZP: {node.weight_zero_point} */")
            lines.append(f"static const int8_t {safe_name}_weight[{w.size}] = {{")
            flat = w.flatten()
            # Write in rows of 16
            for i in range(0, len(flat), 16):
                chunk = flat[i:i+16]
                vals = ", ".join(str(int(v)) for v in chunk)
                comma = "," if i + 16 < len(flat) else ""
                lines.append(f"    {vals}{comma}")
            lines.append("};")
            lines.append(f"static const float {safe_name}_scale = {node.weight_scale:.8f}f;")
            lines.append(f"static const int {safe_name}_zero_point = {node.weight_zero_point};")
            lines.append("")

            # Write bias array
            if node.bias is not None:
                b = node.bias_int32 if node.bias_int32 is not None else \
                    np.round(node.bias).astype(np.int32)
                lines.append(f"static const int32_t {safe_name}_bias[{b.size}] = {{")
                vals = ", ".join(str(int(v)) for v in b.flatten())
                lines.append(f"    {vals}")
                lines.append("};")
                lines.append("")

        # Write shape constants
        lines.append("/* Layer shapes */")
        for node in self.graph.get_compute_nodes():
            if node.eliminated:
                continue
            safe_name = node.name.replace('.', '_')
            if node.output_shape:
                for i, dim in enumerate(node.output_shape):
                    lines.append(f"#define {safe_name.upper()}_DIM{i} {dim}")
                lines.append("")

        lines.append("#endif /* MODEL_WEIGHTS_H */")
        return "\n".join(lines)

    def _generate_ops_header(self) -> str:
        """Generate header with layer operation implementations."""
        lines = [
            "/* Auto-generated by TinyML Compiler */",
            "/* Layer operation implementations - INT8 fixed-point */",
            "",
            "#ifndef MODEL_OPS_H",
            "#define MODEL_OPS_H",
            "",
            "#include <stdint.h>",
            "#include <string.h>",
            "",
            "/* ============================================ */",
            "/* INT8 Conv2D */",
            "/* ============================================ */",
            "static inline void conv2d_int8(",
            "    const int8_t* input, const int8_t* weight, const int32_t* bias,",
            "    int8_t* output,",
            "    int in_c, int in_h, int in_w,",
            "    int out_c, int k_h, int k_w,",
            "    int stride_h, int stride_w,",
            "    int pad_h, int pad_w,",
            "    float input_scale, int input_zp,",
            "    float weight_scale, int weight_zp,",
            "    float output_scale, int output_zp,",
            "    int apply_relu",
            ") {",
            "    int out_h = (in_h + 2 * pad_h - k_h) / stride_h + 1;",
            "    int out_w = (in_w + 2 * pad_w - k_w) / stride_w + 1;",
            "    float m_scale = (input_scale * weight_scale) / output_scale;",
            "",
            "    for (int oc = 0; oc < out_c; oc++) {",
            "        for (int oh = 0; oh < out_h; oh++) {",
            "            for (int ow = 0; ow < out_w; ow++) {",
            "                int32_t acc = 0;",
            "                for (int ic = 0; ic < in_c; ic++) {",
            "                    for (int kh = 0; kh < k_h; kh++) {",
            "                        for (int kw = 0; kw < k_w; kw++) {",
            "                            int ih = oh * stride_h - pad_h + kh;",
            "                            int iw = ow * stride_w - pad_w + kw;",
            "                            int8_t in_val = 0;",
            "                            if (ih >= 0 && ih < in_h && iw >= 0 && iw < in_w) {",
            "                                in_val = input[(ic * in_h + ih) * in_w + iw];",
            "                            }",
            "                            int w_idx = ((oc * in_c + ic) * k_h + kh) * k_w + kw;",
            "                            acc += (int32_t)in_val * (int32_t)weight[w_idx];",
            "                        }",
            "                    }",
            "                }",
            "                if (bias) acc += bias[oc];",
            "                /* Requantize */",
            "                int32_t result = (int32_t)(acc * m_scale) + output_zp;",
            "                if (apply_relu && result < output_zp) result = output_zp;",
            "                if (result > 127) result = 127;",
            "                if (result < -128) result = -128;",
            "                output[(oc * out_h + oh) * out_w + ow] = (int8_t)result;",
            "            }",
            "        }",
            "    }",
            "}",
            "",
            "/* ============================================ */",
            "/* INT8 Linear (Fully Connected) */",
            "/* ============================================ */",
            "static inline void linear_int8(",
            "    const int8_t* input, const int8_t* weight, const int32_t* bias,",
            "    int8_t* output,",
            "    int in_features, int out_features,",
            "    float input_scale, int input_zp,",
            "    float weight_scale, int weight_zp,",
            "    float output_scale, int output_zp,",
            "    int apply_relu",
            ") {",
            "    float m_scale = (input_scale * weight_scale) / output_scale;",
            "    for (int o = 0; o < out_features; o++) {",
            "        int32_t acc = 0;",
            "        for (int i = 0; i < in_features; i++) {",
            "            acc += (int32_t)input[i] * (int32_t)weight[o * in_features + i];",
            "        }",
            "        if (bias) acc += bias[o];",
            "        int32_t result = (int32_t)(acc * m_scale) + output_zp;",
            "        if (apply_relu && result < output_zp) result = output_zp;",
            "        if (result > 127) result = 127;",
            "        if (result < -128) result = -128;",
            "        output[o] = (int8_t)result;",
            "    }",
            "}",
            "",
            "/* ============================================ */",
            "/* INT8 MaxPool2D */",
            "/* ============================================ */",
            "static inline void maxpool2d_int8(",
            "    const int8_t* input, int8_t* output,",
            "    int channels, int in_h, int in_w,",
            "    int k_h, int k_w, int stride_h, int stride_w",
            ") {",
            "    int out_h = (in_h - k_h) / stride_h + 1;",
            "    int out_w = (in_w - k_w) / stride_w + 1;",
            "    for (int c = 0; c < channels; c++) {",
            "        for (int oh = 0; oh < out_h; oh++) {",
            "            for (int ow = 0; ow < out_w; ow++) {",
            "                int8_t max_val = -128;",
            "                for (int kh = 0; kh < k_h; kh++) {",
            "                    for (int kw = 0; kw < k_w; kw++) {",
            "                        int ih = oh * stride_h + kh;",
            "                        int iw = ow * stride_w + kw;",
            "                        int8_t val = input[(c * in_h + ih) * in_w + iw];",
            "                        if (val > max_val) max_val = val;",
            "                    }",
            "                }",
            "                output[(c * out_h + oh) * out_w + ow] = max_val;",
            "            }",
            "        }",
            "    }",
            "}",
            "",
            "/* ============================================ */",
            "/* INT8 ReLU */",
            "/* ============================================ */",
            "static inline void relu_int8(int8_t* data, int size, int zero_point) {",
            "    for (int i = 0; i < size; i++) {",
            "        if (data[i] < (int8_t)zero_point) data[i] = (int8_t)zero_point;",
            "    }",
            "}",
            "",
            "/* ============================================ */",
            "/* Flatten (reinterpret - no-op for contiguous) */",
            "/* ============================================ */",
            "/* Flatten is a no-op in C when data is contiguous in memory */",
            "",
            "#endif /* MODEL_OPS_H */",
        ]
        return "\n".join(lines)

    def _generate_main_header(self) -> str:
        """Generate main model header."""
        # Determine input/output sizes
        in_size, out_size = 0, 0
        for node in self.graph.nodes:
            if node.op_type == OpType.PLACEHOLDER and node.output_shape:
                in_size = 1
                for d in node.output_shape:
                    in_size *= d
            if node.op_type == OpType.OUTPUT and node.inputs:
                out_node = self.graph.get_node(node.inputs[0])
                if out_node and out_node.output_shape:
                    out_size = 1
                    for d in out_node.output_shape:
                        out_size *= d

        lines = [
            "/* Auto-generated by TinyML Compiler */",
            f"/* Model: {self.graph.model_name} */",
            "",
            "#ifndef MODEL_H",
            "#define MODEL_H",
            "",
            "#include <stdint.h>",
            "",
            f"#define MODEL_INPUT_SIZE {in_size}",
            f"#define MODEL_OUTPUT_SIZE {out_size}",
            "",
            "/* Run inference */",
            "void run_model(const int8_t* input, int8_t* output);",
            "",
            "#endif /* MODEL_H */",
        ]
        return "\n".join(lines)

    def _generate_model_c(self) -> str:
        """Generate the main model.c file with inference function."""
        lines = [
            "/* Auto-generated by TinyML Compiler */",
            f"/* Model: {self.graph.model_name} */",
            "/* WARNING: This file is auto-generated. Do not edit. */",
            "",
            '#include "model.h"',
            '#include "model_weights.h"',
            '#include "model_ops.h"',
            "",
        ]

        # Calculate buffer sizes needed
        compute_nodes = self.graph.get_compute_nodes()
        max_activation_size = 0
        for n in compute_nodes:
            size = n.activation_memory_bytes()
            if size > max_activation_size:
                max_activation_size = size

        # Use two alternating static buffers
        lines.append(f"/* Static activation buffers (double-buffered) */")
        lines.append(f"static int8_t buffer_a[{max(max_activation_size, 1)}];")
        lines.append(f"static int8_t buffer_b[{max(max_activation_size, 1)}];")
        lines.append("")

        # Generate inference function
        lines.append("void run_model(const int8_t* input, int8_t* output) {")
        lines.append("    const int8_t* current_input = input;")
        lines.append("    int8_t* current_output;")
        lines.append("    int use_buffer_a = 1;")
        lines.append("")

        for node in compute_nodes:
            if node.eliminated:
                continue
            layer_code = self._generate_layer_call(node)
            if layer_code:
                lines.extend(["    " + l for l in layer_code])
                lines.append("")

        # Copy final result to output
        last_compute = None
        for n in reversed(compute_nodes):
            if not n.eliminated:
                last_compute = n
                break
        if last_compute and last_compute.output_shape:
            out_size = 1
            for d in last_compute.output_shape:
                out_size *= d
            lines.append(f"    /* Copy result to output */")
            lines.append(f"    memcpy(output, current_input, {out_size});")

        lines.append("}")
        lines.append("")

        # Generate a simple main() for testing
        lines.extend(self._generate_test_main())

        return "\n".join(lines)

    def _generate_layer_call(self, node: IRNode) -> List[str]:
        """Generate C code for a single layer call."""
        safe_name = node.name.replace('.', '_')
        lines = []

        i_scale = node.input_scale or 0.023529
        i_zp = node.input_zero_point or 0
        o_scale = node.output_scale or 0.023529
        o_zp = node.output_zero_point or 0
        w_scale = node.weight_scale or 0.01
        w_zp = node.weight_zero_point or 0

        if node.op_type in (OpType.CONV2D, OpType.FUSED_CONV_RELU):
            p = node.params
            ic = p.get('in_channels', 1)
            ks = p.get('kernel_size', (3, 3))
            k = ks[0] if isinstance(ks, tuple) else ks
            stride = p.get('stride', (1, 1))
            s = stride[0] if isinstance(stride, tuple) else stride
            padding = p.get('padding', (0, 0))
            pad = padding[0] if isinstance(padding, tuple) else padding
            oc = p.get('out_channels', 1)

            in_shape = node.input_shape
            ih = in_shape[2] if in_shape and len(in_shape) == 4 else 1
            iw = in_shape[3] if in_shape and len(in_shape) == 4 else 1
            relu = 1 if node.op_type == OpType.FUSED_CONV_RELU else 0
            bias_arg = f"{safe_name}_bias" if node.bias is not None else "NULL"

            lines.append(f"/* {node.name}: {node.op_type.value} */")
            lines.append(f"current_output = use_buffer_a ? buffer_a : buffer_b;")
            lines.append(f"conv2d_int8(current_input, {safe_name}_weight, {bias_arg},")
            lines.append(f"    current_output, {ic}, {ih}, {iw}, {oc}, {k}, {k},")
            lines.append(f"    {s}, {s}, {pad}, {pad},")
            lines.append(f"    {i_scale:.8f}f, {i_zp}, {w_scale:.8f}f, {w_zp},")
            lines.append(f"    {o_scale:.8f}f, {o_zp}, {relu});")
            lines.append(f"current_input = current_output;")
            lines.append(f"use_buffer_a = !use_buffer_a;")

        elif node.op_type in (OpType.LINEAR, OpType.FUSED_LINEAR_RELU):
            p = node.params
            in_f = p.get('in_features', 1)
            out_f = p.get('out_features', 1)
            relu = 1 if node.op_type == OpType.FUSED_LINEAR_RELU else 0
            bias_arg = f"{safe_name}_bias" if node.bias is not None else "NULL"

            lines.append(f"/* {node.name}: {node.op_type.value} */")
            lines.append(f"current_output = use_buffer_a ? buffer_a : buffer_b;")
            lines.append(f"linear_int8(current_input, {safe_name}_weight, {bias_arg},")
            lines.append(f"    current_output, {in_f}, {out_f},")
            lines.append(f"    {i_scale:.8f}f, {i_zp}, {w_scale:.8f}f, {w_zp},")
            lines.append(f"    {o_scale:.8f}f, {o_zp}, {relu});")
            lines.append(f"current_input = current_output;")
            lines.append(f"use_buffer_a = !use_buffer_a;")

        elif node.op_type == OpType.MAXPOOL2D:
            p = node.params
            ks = p.get('kernel_size', (2, 2))
            k = ks[0] if isinstance(ks, tuple) else ks
            stride = p.get('stride', (2, 2))
            s = stride[0] if isinstance(stride, tuple) else stride
            in_shape = node.input_shape
            c = in_shape[1] if in_shape and len(in_shape) == 4 else 1
            ih = in_shape[2] if in_shape and len(in_shape) == 4 else 1
            iw = in_shape[3] if in_shape and len(in_shape) == 4 else 1

            lines.append(f"/* {node.name}: maxpool2d */")
            lines.append(f"current_output = use_buffer_a ? buffer_a : buffer_b;")
            lines.append(f"maxpool2d_int8(current_input, current_output, {c}, {ih}, {iw}, {k}, {k}, {s}, {s});")
            lines.append(f"current_input = current_output;")
            lines.append(f"use_buffer_a = !use_buffer_a;")

        elif node.op_type == OpType.RELU:
            out_size = node.activation_memory_bytes() or 1
            lines.append(f"/* {node.name}: relu */")
            lines.append(f"relu_int8((int8_t*)current_input, {out_size}, {o_zp});")

        elif node.op_type == OpType.FLATTEN:
            lines.append(f"/* {node.name}: flatten (no-op in C) */")

        return lines

    def _generate_test_main(self) -> List[str]:
        """Generate a simple test main function."""
        return [
            "",
            "#ifdef TEST_MODEL",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "",
            "int main() {",
            "    int8_t input[MODEL_INPUT_SIZE];",
            "    int8_t output[MODEL_OUTPUT_SIZE];",
            "",
            "    /* Initialize with zeros */",
            "    memset(input, 0, sizeof(input));",
            "",
            "    /* Run inference */",
            "    run_model(input, output);",
            "",
            '    printf("Inference complete.\\n");',
            '    printf("Output values: ");',
            "    for (int i = 0; i < MODEL_OUTPUT_SIZE; i++) {",
            '        printf("%d ", output[i]);',
            "    }",
            '    printf("\\n");',
            "",
            "    return 0;",
            "}",
            "#endif /* TEST_MODEL */",
        ]

    def _write_file(self, filename: str, content: str):
        """Write content to a file in the output directory."""
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w') as f:
            f.write(content)
        self._log(f"  Generated: {filepath}")

    def _log(self, msg: str):
        if self.verbose:
            print(f"[CodeGen] {msg}")


if __name__ == "__main__":
    import torch
    import torch.nn as nn
    from frontend.graph_extractor import GraphExtractor
    from ir.ir_builder import IRBuilder
    from optimizer.graph_optimizer import GraphOptimizer
    from quantization.int8_quantizer import INT8Quantizer

    class TestCNN(nn.Module):
        def __init__(self):
            super().__init__()
            self.conv1 = nn.Conv2d(1, 16, 3, padding=1)
            self.relu1 = nn.ReLU()
            self.pool1 = nn.MaxPool2d(2)
            self.flatten = nn.Flatten()
            self.fc1 = nn.Linear(16 * 14 * 14, 10)
        def forward(self, x):
            return self.fc1(self.flatten(self.pool1(self.relu1(self.conv1(x)))))

    model = TestCNN()
    sample = torch.randn(1, 1, 28, 28)
    graph = GraphExtractor(model, sample).extract()
    ir = IRBuilder(model, graph).build()
    ir = GraphOptimizer(ir, verbose=False).optimize()
    ir = INT8Quantizer(ir, verbose=False).quantize()
    gen = CCodeGenerator(ir, output_dir="generated_test")
    gen.generate()
    print("\nC code generation test passed!")
