# -*- coding: utf-8 -*-
"""Deep Learning Programming Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TwHccry3DJuQm5cz68DlNl1HVe6yLewX
"""

# CSL7590: Deep Learning, Programming Assignment
# This script provides a complete framework for the assignment.
# It includes implementations for Sparse, Contractive, and Variational Autoencoders.

# Make sure to have a 'results' directory in the same folder as this script.
# All plots and outputs will be saved there.

# For the Frey Face dataset, you'll need to download it manually.
# A common source is: https://cs.nyu.edu/~roweis/data/frey_rawface.mat
# Place the 'frey_rawface.mat' file in a 'data' subdirectory.

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torchvision.datasets import MNIST
from torchvision import transforms
import numpy as np
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import os
import scipy.io

# --- General Setup ---
# Create directories to save results if they don't exist
if not os.path.exists('results'):
    os.makedirs('results')
if not os.path.exists('data'):
    os.makedirs('data')

# Set device (use GPU if available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# --- Part 1: Sparse and Contractive Autoencoders ---

# 1.1 Data Loading and Preprocessing for MNIST
transform = transforms.Compose([
    transforms.ToTensor(),
    # Normalizing is important for training stability
    transforms.Normalize((0.5,), (0.5,))
])

# Download and load the MNIST dataset
mnist_train = MNIST(root='./data', train=True, transform=transform, download=True)
mnist_test = MNIST(root='./data', train=False, transform=transform, download=True)

train_loader = DataLoader(mnist_train, batch_size=128, shuffle=True)
test_loader = DataLoader(mnist_test, batch_size=128, shuffle=False)

# 1.2 Model Architecture (U-Net style without skip connections)
class Autoencoder(nn.Module):
    def __init__(self, embedding_dim=64):
        super(Autoencoder, self).__init__()
        # Encoder
        self.encoder = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(True),
            nn.Linear(512, 256),
            nn.ReLU(True),
            nn.Linear(256, 128),
            nn.ReLU(True),
            nn.Linear(128, embedding_dim) # This is our embedding h
        )
        # Decoder
        self.decoder = nn.Sequential(
            nn.Linear(embedding_dim, 128),
            nn.ReLU(True),
            nn.Linear(128, 256),
            nn.ReLU(True),
            nn.Linear(256, 512),
            nn.ReLU(True),
            nn.Linear(512, 28 * 28),
            nn.Tanh() # Tanh activation to match the normalized input range [-1, 1]
        )

    def forward(self, x):
        h = self.encoder(x)
        x_hat = self.decoder(h)
        return x_hat, h

# 1.3 Loss Functions and Training Loops

# Reconstruction Loss
reconstruction_loss_fn = nn.MSELoss()

# Sparsity Penalty (KL Divergence)
def kl_divergence(rho, rho_hat):
    rho_hat = torch.mean(torch.sigmoid(rho_hat), 1) # Average activation for each neuron
    rho = torch.tensor([rho] * len(rho_hat)).to(device)
    return torch.sum(rho * torch.log(rho/rho_hat) + (1-rho) * torch.log((1-rho)/(1-rho_hat)))

# Training function for Sparse Autoencoder
def train_sparse_ae(model, dataloader, epochs=20, learning_rate=1e-3, sparsity_param=0.05, sparsity_weight=1e-4):
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)
    model.train()
    print("--- Training Sparse Autoencoder ---")
    for epoch in range(epochs):
        total_loss = 0
        for data in dataloader:
            img, _ = data
            img = img.view(img.size(0), -1).to(device)

            # Forward pass
            output, hidden = model(img)

            # Calculate losses
            recon_loss = reconstruction_loss_fn(output, img)
            sparsity_loss = kl_divergence(sparsity_param, hidden)
            loss = recon_loss + sparsity_weight * sparsity_loss

            # Backward pass and optimization
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        print(f'Epoch [{epoch+1}/{epochs}], Loss: {total_loss/len(dataloader):.4f}')
    print("--- Sparse Autoencoder Training Finished ---")
    return model

# Training function for Contractive Autoencoder
def train_contractive_ae(model, dataloader, epochs=20, learning_rate=1e-3, contractive_weight=1e-4):
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)
    model.train()
    print("--- Training Contractive Autoencoder ---")
    for epoch in range(epochs):
        total_loss = 0
        for data in dataloader:
            img, _ = data
            img = img.view(img.size(0), -1).to(device)
            img.requires_grad = True # We need gradients with respect to the input

            # Forward pass
            output, hidden = model(img)

            # Calculate reconstruction loss
            recon_loss = reconstruction_loss_fn(output, img)

            # Calculate contractive penalty
            # We need the Jacobian of the hidden layer with respect to the input
            J = torch.autograd.grad(hidden, img, grad_outputs=torch.ones_like(hidden), create_graph=True)[0]
            contractive_loss = torch.sum(J ** 2)

            loss = recon_loss + contractive_weight * contractive_loss

            # Backward pass and optimization
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        print(f'Epoch [{epoch+1}/{epochs}], Loss: {total_loss/len(dataloader):.4f}')
    print("--- Contractive Autoencoder Training Finished ---")
    return model

# 1.4 Analysis Functions

# (a) t-SNE Plot
def plot_tsne(model, dataloader, title):
    print(f"--- Generating t-SNE plot for {title} ---")
    model.eval()
    embeddings = []
    labels = []
    with torch.no_grad():
        for data in dataloader:
            img, label = data
            img = img.view(img.size(0), -1).to(device)
            _, h = model(img)
            embeddings.append(h.cpu().numpy())
            labels.append(label.cpu().numpy())

    embeddings = np.concatenate(embeddings, axis=0)
    labels = np.concatenate(labels, axis=0)

    tsne = TSNE(n_components=2, random_state=42, n_iter=300, perplexity=30)
    tsne_results = tsne.fit_transform(embeddings)

    plt.figure(figsize=(10, 8))
    scatter = plt.scatter(tsne_results[:, 0], tsne_results[:, 1], c=labels, cmap='tab10', s=5)
    plt.legend(handles=scatter.legend_elements()[0], labels=list(range(10)))
    plt.title(f't-SNE of MNIST Embeddings ({title})')
    plt.savefig(f'results/tsne_{title.lower().replace(" ", "_")}.png')
    plt.show()

# (b) Image Interpolation
def image_interpolation(model, dataloader, title, num_pairs=5): # Reduced to 5 for quicker run, change to 20 for submission
    print(f"--- Performing Image Interpolation for {title} ---")
    model.eval()
    dataset = dataloader.dataset

    # Get images from different classes
    pairs = []
    for i in range(10):
        for j in range(i + 1, 10):
            if len(pairs) >= num_pairs:
                break
            idx1 = np.where(np.array(dataset.targets) == i)[0][0]
            idx2 = np.where(np.array(dataset.targets) == j)[0][0]
            img1, _ = dataset[idx1]
            img2, _ = dataset[idx2]
            pairs.append((img1, img2))
        if len(pairs) >= num_pairs:
            break

    alpha_values = [0, 0.2, 0.4, 0.6, 0.8, 1.0]

    for pair_idx, (img1, img2) in enumerate(pairs):
        img1 = img1.view(1, -1).to(device)
        img2 = img2.view(1, -1).to(device)

        with torch.no_grad():
            h1 = model.encoder(img1)
            h2 = model.encoder(img2)

        fig, axes = plt.subplots(4, len(alpha_values), figsize=(15, 10))
        fig.suptitle(f'Interpolation Pair {pair_idx+1} ({title})', fontsize=16)

        psnr_vals = []
        dist_vals = []

        for i, alpha in enumerate(alpha_values):
            # Image space interpolation
            I_alpha = alpha * img1 + (1 - alpha) * img2
            I_hat_alpha, h_alpha = model(I_alpha)

            # Latent space interpolation
            h_prime_alpha = alpha * h1 + (1 - alpha) * h2
            I_hat_prime_alpha = model.decoder(h_prime_alpha)

            # Calculate PSNR and distance
            mse = torch.mean((I_hat_alpha - I_hat_prime_alpha) ** 2)
            psnr = 20 * torch.log10(1.0 / torch.sqrt(mse)) # Assuming max pixel value is 1.0 after normalization
            dist = torch.norm(h_alpha - h_prime_alpha, 2)
            psnr_vals.append(psnr.item())
            dist_vals.append(dist.item())

            # Plotting
            axes[0, i].imshow(I_alpha.cpu().detach().numpy().reshape(28, 28), cmap='gray')
            axes[0, i].set_title(f'I_alpha (a={alpha})')
            axes[0, i].axis('off')

            axes[1, i].imshow(I_hat_alpha.cpu().detach().numpy().reshape(28, 28), cmap='gray')
            axes[1, i].set_title(f'I_hat_alpha')
            axes[1, i].axis('off')

            axes[2, i].imshow(I_hat_prime_alpha.cpu().detach().numpy().reshape(28, 28), cmap='gray')
            axes[2, i].set_title(f'I_hat_prime_alpha')
            axes[2, i].axis('off')

            axes[3, i].text(0.5, 0.5, f'PSNR: {psnr.item():.2f}\nDist: {dist.item():.2f}', ha='center', va='center')
            axes[3, i].axis('off')

        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        plt.savefig(f'results/interpolation_{title.lower().replace(" ", "_")}_pair_{pair_idx+1}.png')
        plt.show()

        print(f"Pair {pair_idx+1} PSNRs: {psnr_vals}")
        print(f"Pair {pair_idx+1} Distances: {dist_vals}")


# (c) Classification on Embeddings
def classify_embeddings(model, train_loader, test_loader, title):
    print(f"--- Classifying Embeddings for {title} ---")
    model.eval()

    # Get training embeddings
    X_train, y_train = [], []
    with torch.no_grad():
        for img, label in train_loader:
            img = img.view(img.size(0), -1).to(device)
            _, h = model(img)
            X_train.append(h.cpu().numpy())
            y_train.append(label.cpu().numpy())
    X_train = np.concatenate(X_train, axis=0)
    y_train = np.concatenate(y_train, axis=0)

    # Get test embeddings
    X_test, y_test = [], []
    with torch.no_grad():
        for img, label in test_loader:
            img = img.view(img.size(0), -1).to(device)
            _, h = model(img)
            X_test.append(h.cpu().numpy())
            y_test.append(label.cpu().numpy())
    X_test = np.concatenate(X_test, axis=0)
    y_test = np.concatenate(y_test, axis=0)

    # Train SVM classifier
    print("Training SVM...")
    classifier = SVC(kernel='rbf', C=1.0, gamma='scale')
    classifier.fit(X_train, y_train)

    # Evaluate
    print("Evaluating...")
    y_pred = classifier.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    print(f"Classification Accuracy for {title}: {accuracy * 100:.2f}%")
    return accuracy

# --- Part 2: Variational Autoencoder (VAE) ---

# 2.1 Frey Face Dataset Loading
class FreyFaceDataset(Dataset):
    def __init__(self, file_path, transform=None):
        mat = scipy.io.loadmat(file_path)
        # Data is in shape (1965, 560), needs to be (1965, 28, 20)
        self.data = mat['ff'].T.reshape((-1, 28, 20))
        self.transform = transform

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sample = self.data[idx]
        # Convert to float32 and scale to [0, 1]
        sample = sample.astype(np.float32) / 255.0
        if self.transform:
            sample = self.transform(sample)
        return sample, 0 # Return 0 as a dummy label

# 2.2 VAE Model Architecture
class VAE(nn.Module):
    def __init__(self, input_dim=28*20, hidden_dim=200, latent_dim=20):
        super(VAE, self).__init__()
        self.input_dim = input_dim
        # Encoder
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim//2),
            nn.ReLU(),
        )
        self.fc_mu = nn.Linear(hidden_dim//2, latent_dim)
        self.fc_log_var = nn.Linear(hidden_dim//2, latent_dim)

        # Decoder
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim//2),
            nn.ReLU(),
            nn.Linear(hidden_dim//2, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, input_dim),
            nn.Sigmoid() # Sigmoid for output in range [0, 1]
        )

    def encode(self, x):
        h = self.encoder(x)
        return self.fc_mu(h), self.fc_log_var(h)

    def reparameterize(self, mu, log_var):
        std = torch.exp(0.5 * log_var)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        return self.decoder(z)

    def forward(self, x):
        mu, log_var = self.encode(x.view(-1, self.input_dim))
        z = self.reparameterize(mu, log_var)
        return self.decode(z), mu, log_var

# 2.3 VAE Loss Function and Training
def vae_loss_function(recon_x, x, mu, log_var):
    # Use Binary Cross-Entropy for reconstruction loss for sigmoid output
    BCE = nn.functional.binary_cross_entropy(recon_x, x.view(-1, 28*20), reduction='sum')
    # KL divergence loss
    KLD = -0.5 * torch.sum(1 + log_var - mu.pow(2) - log_var.exp())
    return BCE + KLD

def train_vae(model, dataloader, epochs=50, learning_rate=1e-3):
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)
    model.train()
    print("--- Training Variational Autoencoder ---")
    for epoch in range(epochs):
        total_loss = 0
        for data, _ in dataloader:
            data = data.to(device)
            optimizer.zero_grad()
            recon_batch, mu, log_var = model(data)
            loss = vae_loss_function(recon_batch, data, mu, log_var)
            loss.backward()
            total_loss += loss.item()
            optimizer.step()

        print(f'Epoch [{epoch+1}/{epochs}], Loss: {total_loss / len(dataloader.dataset):.4f}')
    print("--- VAE Training Finished ---")
    return model

# 2.4 VAE Evaluation (Sampling from Latent Space)
def sample_from_vae(model, num_samples=20, latent_dim=20):
    print("--- Sampling from VAE Latent Space ---")
    model.eval()
    with torch.no_grad():
        # Generate random samples from the latent space (prior distribution)
        z = torch.randn(num_samples, latent_dim).to(device)
        samples = model.decode(z).cpu()

    # Plot the generated samples
    fig, axes = plt.subplots(4, 5, figsize=(8, 8))
    for i, ax in enumerate(axes.flat):
        ax.imshow(samples[i].view(28, 20), cmap='gray')
        ax.axis('off')
    plt.suptitle('Random Samples from VAE Latent Space')
    plt.savefig('results/vae_random_samples.png')
    plt.show()

# --- Main Execution Block ---
if __name__ == '__main__':
    # --- Problem 1 Execution ---
    print("=============== STARTING PROBLEM 1 ===============")

    # Train and evaluate Sparse AE
    sparse_ae = Autoencoder().to(device)
    sparse_ae = train_sparse_ae(sparse_ae, train_loader, epochs=10) # Reduced epochs for demo
    plot_tsne(sparse_ae, test_loader, "Sparse AE")
    image_interpolation(sparse_ae, test_loader, "Sparse AE")
    classify_embeddings(sparse_ae, train_loader, test_loader, "Sparse AE")

    # Train and evaluate Contractive AE
    contractive_ae = Autoencoder().to(device)
    contractive_ae = train_contractive_ae(contractive_ae, train_loader, epochs=10) # Reduced epochs for demo
    plot_tsne(contractive_ae, test_loader, "Contractive AE")
    image_interpolation(contractive_ae, test_loader, "Contractive AE")
    classify_embeddings(contractive_ae, train_loader, test_loader, "Contractive AE")

    print("=============== FINISHED PROBLEM 1 ===============")

    # --- Problem 2 Execution ---
    print("\n=============== STARTING PROBLEM 2 ===============")

    frey_face_path = './data/frey_rawface.mat'
    if not os.path.exists(frey_face_path):
        print("\nERROR: Frey Face dataset not found.")
        print("Please download 'frey_rawface.mat' from https://cs.nyu.edu/~roweis/data/frey_rawface.mat")
        print("And place it in the 'data' directory.\n")
    else:
        frey_transform = transforms.ToTensor()
        frey_dataset = FreyFaceDataset(file_path=frey_face_path, transform=frey_transform)
        frey_loader = DataLoader(frey_dataset, batch_size=64, shuffle=True)

        vae = VAE().to(device)
        vae = train_vae(vae, frey_loader, epochs=50) # VAEs often need more epochs
        sample_from_vae(vae)

    print("=============== FINISHED PROBLEM 2 ===============")